server:
  port: 8081

management:
  info:
    git:
      mode: full
  endpoints:
    web:
      exposure:
        include: health,info

spring:
  application:
    name: skillShare

  datasource:
    url: jdbc:postgresql://localhost:5432/skillsharedb
    username: shubhamjain
    password: none
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger
    enabled: true